name: Build SomeVer

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    runs-on: windows-2022
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Build SomeVer
        shell: cmd
        run: build.cmd

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4.3.1
        with:
          name: artifacts
          path: ./**/*.nupkg

      - name: Push to GitHub Packages
        if: github.event_name == 'push' && github.repository_owner == 'robmen' && github.ref == 'refs/heads/main'
        run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/robmen/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
